### ISSUE TITLE
Uncaught exception when trying to connect

### ISSUE THREAD

**Issue by mikestreety** [activecollab/activecollab-feather-sdk#10]
Hello,

This issue started today when accessing the API. No matter what login credentials I use, it does not seem to work.

Thanks!

```
PHP Fatal error:  Uncaught exception 'ActiveCollab\SDK\Exceptions\Authentication' with message 'Invalid response' in vendor/activecollab/activecollab-feather-sdk/src/Authenticator/Cloud.php:126
Stack trace:
#0 test-ac.php(13): ActiveCollab\SDK\Authenticator\Cloud->issueToken(000000)
#1 {main}
  thrown in vendor/activecollab/activecollab-feather-sdk/src/Authenticator/Cloud.php on line 126
```

**Comment by thomaspalmer** [comment]
This issue is effecting us as well, can we get an ETA when this will be resolved.

**Comment by mikestreety** [comment]
@thomaspalmer Seems to be a global API issue which is having side-affects in AC as well.

**Comment by timothybannister** [comment]
Im having the same issue since yesterday around 1300 GMT I emailed support but they just said they are look at the issue after a rollout.
#PHPUnit perhaps :)

**Comment by thomaspalmer** [comment]
Seems to be working now!

**Comment by mikestreety** [comment]
Just had the same thought/experience.

**Comment by mikestreety** [comment]
It worked, now it doesn't again.

😒

**Comment by cleberalves** [comment]
Hello! No solution yet?

**Comment by ilijastuden** [comment]
That was a temporal issue, on our end. There are no known problems with authentication ATM.
