### ISSUE TITLE
GET with Query Parameters ?

### ISSUE THREAD

**Issue by jcrombez** [activecollab/activecollab-feather-sdk#13]
How are we supposed to specify Query Parameters with this SDK when using GET ?
I don't see any second parameter for the ```Client::get``` method.

For simple things i can do this :
```php
$client->get('reports/run?type=InvoicesFilter');
```
But for more advanced parameters, it becomes a mess.

**Comment by ilijastuden** [comment]
That's how library works at the moment. You can always use PHP's [http_build_query() function](http://php.net/manual/en/function.http-build-query.php) to prepare a query from an associative array.

**Comment by jcrombez** [comment]
Ok thanks you for the tips.
It would be nice to have a second parameter though :)

**Comment by ilijastuden** [comment]
Thanks for the suggestion, we'll keep it in mind for furutre updates. This is GitHub, so good old "PR is welcome" applies if you would like to see it sooner. Social coding FTW 👍

**Comment by jcrombez** [comment]
I'll try to find some time for it :)
