### ISSUE TITLE
CURLOPT_SAFE_UPLOAD option unsupported in PHP 7 

### ISSUE THREAD

**Issue by towerdev** [activecollab/activecollab-feather-sdk#15]
In PHP 7, the `CURLOPT_SAFE_UPLOAD` flag as set in Connector.php in the `post` method does not work in PHP 7 ([seen here](https://github.com/activecollab/activecollab-feather-sdk/blob/master/src/Connector.php#L97)). This raises an ErrorException with the message:

 `setopt(): Disabling safe uploads is no longer supported`

**Comment by ilijastuden** [comment]
Fix is in `master`. Version 3.2 will have it included.
