### ISSUE TITLE
API revision - /projects/<#>/tasks/<should be task_number, not task_id>

### ISSUE THREAD

**Issue by bottydim** [activecollab/activecollab-feather-sdk#17]
It doesn't make sense to me to access the project, so that I will have to access the task using its global id rather than the project task id, which is the "task_number" field

**Comment by ilijastuden** [comment]
This is an unlikely change, due to backward compatibility and consistency (there's no other API that exposes elements via context specific ID, instead of their actual ID-s).

#16 is likely to happen.

**Comment by bottydim** [comment]
@ilijastuden As it is particularly important to be able to use the task_number rather than the task_id, there should be a way of doing that. I don't think it should be up to the developer to build a dictionary for each project.

Use case: my team needs to sync toggl and active-collab through the API. When we open the task window, it shows us the task_number rather than the task_id. I need some information to log to my toggl task, so that it sync's with active-collab task. Hence, the unnecessary dictionary, as we don't have an easy way to see the task_id.

**Comment by ilijastuden** [comment]
That's an interesting use case. I've added introduction of *new* API end point that uses per-project ID to our backlog. Not that it can't be implemented as suggested. Altering a widely used API end-point would break all sorts of integrations that are already developed.

PS: Global task # is easily accessible from browser's address bar.
