### ISSUE TITLE
Invalid response. JSON expected

### ISSUE THREAD

**Issue by sarvesh123** [activecollab/activecollab-feather-sdk#18]
Fatal error: Uncaught exception 'ActiveCollab\SDK\Exceptions\Authentication' with message 'Invalid response. JSON expected, got "text/html;charset=UTF-8", status code "200"' in D:\webroot\activecollab-feather-sdk\src\Authenticator\SelfHosted.php:76 Stack trace: #0 D:\webroot\activecollab-feather-sdk\get_projects.php(15): ActiveCollab\SDK\Authenticator\SelfHosted->issueToken() #1 {main} thrown in D:\webroot\activecollab-feather-sdk\src\Authenticator\SelfHosted.php on line 76

Below is the code 
require_once __DIR__ . '/vendor/autoload.php';

// Construct a self-hosted authenticator. Last parameter is URL where your Active Collab
$authenticator = new \ActiveCollab\SDK\Authenticator\SelfHosted('Some Company Name', 'Report', 'some email', 'some password', 'https://xxx.yyy.com/projects');

// Issue a token
$token = $authenticator->issueToken();

if ($token instanceof \ActiveCollab\SDK\TokenInterface) {
    print $token->getUrl() . "\n";
    print $token->getToken() . "\n";
} else {
    print "Invalid response\n";
    die();
}

// Create a client instance
$client = new \ActiveCollab\SDK\Client($token);

// Make a request
print_r($client->get('projects'));

**Comment by sarveshshejwadkar** [comment]
the issue got resolved when i remove "/projects" from 'https://xxx.yyy.com/projects'
