### ISSUE TITLE
PUT comment without (email) notification

### ISSUE THREAD

**Issue by 7elix** [activecollab/activecollab-feather-sdk#2]
When adding comments to issues a flag to ignore-notification / do-not-send-notification email should exist. This makes sense for comments that are added by robots/web hooks. Those should not always trigger email notifications.

**Comment by ilijastuden** [comment]
That feature already exists - just set `notify_subscribers` to `false` when sending a POST command to comments resource.

**Comment by 7elix** [comment]
Thanks, great.

Would be great if the parameter could be added here also
https://labs.activecollab.com/nightly-activecollab-api/v1/projects/elements/tasks/comments.html

Cheers!
