### ISSUE TITLE
ActiveCollab authentication API issue

### ISSUE THREAD

**Issue by SolvingMan** [activecollab/activecollab-feather-sdk#25]
I have tested activecollab api using postman.

> https://my.activecollab.com/api/v1/external/login?email="***@gmail.com"&password="****"&type="Member"

The response is: { "is_ok": false, "message": "Login failed" }

Please some lead me.
Thanks

**Comment by ilijastuden** [comment]
Please check this StackOverflow answer for details: https://stackoverflow.com/a/34685298/338473
