### ISSUE TITLE
Data inconsistency

### ISSUE THREAD

**Issue by Nabarajc** [activecollab/activecollab-feather-sdk#30]
Hello Devs,

I have a issue with the the output of the API.

I'm trying to build a system where i integrate active collab too and trying to fetch tasks and tasks related time records. All works fine but there is inconsistency in the time record values.

Please see the screenshot below:
https://prnt.sc/wfr5ak

In the above screenshot the time tracked values are 0.10 and 0.26 respectively.

Upon fetching the time records via the API with endpoint /projects/1/tasks/1/time-records, the values are different. The screenshot for the response array is attached below:
https://prnt.sc/wfr4wz

The above screenshot have values 0.17 and 0.46 respectively which is completely wrong!

I'm not sure why that is happening? Can you guys let me know if i'm doing anything wrong there?

**Comment by ilijastuden** [comment]
Interface shows values in HH:MM format, while API returns decimal values. More info here: https://stackoverflow.com/a/65563248/338473.
