### ISSUE TITLE
Can this be used by an application on another server?

### ISSUE THREAD

**Issue by EEKimS** [activecollab/activecollab-feather-sdk#4]
I am having huge troubles connecting to the API for activecollab 5 using curl commands, is it possible to use this library to help?

**Comment by ilijastuden** [comment]
This library uses curl to make requests, but everything's set so you don't have to worry about that. Please check README.md for examples how to use the library.

**Comment by EEKimS** [comment]
Sorry for the slow reply, this response doesn't help me very much, i am trying to figure out what to do with this
`require_once '/path/to/vendor/autoload.php';`
on a third party server, if possible, as my tools that use the Active Collab API are not on the same server due to our current set up.

**Comment by ilijastuden** [comment]
Active Collab SDK is primarily installed using Composer, and autoload.php is autoload file prepared by Composer when you run `composer install` or `composer update`.

This is Composer's official website:

https://getcomposer.org

There are many getting started tutorials that will guide you through the basics. Just Google Composer tutorial.

**Comment by ilijastuden** [comment]
PS: …and yes, you can use this SDK to make API requests to Active Collab that is hosted on a different server.

**Comment by EEKimS** [comment]
Alrighty, thank you for your help, my brain was melting
