### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by mmaarten** [activecollab/activecollab-feather-sdk#6]
Hi,

I have made a custom AC Timer for our company iValue.
https://ivalue.be/timer/

Since today we have an authentication issue.
When I want to login I get following error 'Invalid response'.

I am user Active Collab Feather SDK to communicate with the API
https://github.com/activecollab/activecollab-feather-sdk

The exception is throwed when I instantiate the authenticator:
`$authenticator = new \ActiveCollab\SDK\Authenticator\Cloud( IV_APPLICATION_COMPANY, IV_APPLICATION_NAME, $username, $password );`

Can you please help?

Thank you.

Kind regards,

Maarten

**Comment by ilijastuden** [comment]
Hello Maarten,

Was there any change on Active Collab end? Upgrade, or some code alteration? Permission changes? User account being moved to archive or trash?

**Comment by mmaarten** [comment]
Hello Ilijastuden,

Thank you for the quick response.

`Was there any change on Active Collab end? Upgrade, or some code alteration? Permission changes? User account being moved to archive or trash? `

There were no updates, I can login with the account I use in AC.

I have more information concerning the issue:

I dumped the response on
Authentication/Cloud.php issueToken function (line: 104)

```
["raw_response":"ActiveCollab\SDK\Response":private]=>
  string(226) "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
"
```

**Comment by mmaarten** [comment]
Hi,

The authentication with the api works again.

Could have been an issue in AC side.

Thanks
