### ISSUE TITLE
How to use API

### ISSUE THREAD

**Issue by raghumalve** [activecollab/activecollab-feather-sdk#8]
We want to use AC for many projects that we have. We will need to create many projects and task which need to be assigned to loads of users. We will also need to download timesheet data for reporting in other tools. We are exploring using APIs to create all the related configuration.

Is there a how to document for end users on how to use APIs?

**Comment by ilijastuden** [comment]
Check out `README.md` of this package, as well as this section - it shows many scenarios how API can be use to achieve all sorts of things:

https://developers.activecollab.com/api-documentation/

It's not 100% up to date with what API can do, but it will give you pretty clear idea what to expect.
